/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dairyfloater;

import static spark.Spark.*;

import spark.Spark;

public class App {

    public static void main(String[] args) {
        
        staticFiles.location("/public");
        port(8000);
        get("/test", (req, res) -> {
            res.redirect("index.html");
        return null;
        });

        Spark.post("/api/message", (req, res) -> {
            return "Hi, this API call worked";
        });
       }
}
