/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dairyfloater;

import static spark.Spark.*;

import spark.Spark;

public class App {

    public String getGreeting() {
        return "yes";
    }

    public static void main(String[] args) {

        HalfHourIntervals schedule = new HalfHourIntervals();

        staticFiles.location("/public");
        port(8080);
        get("/test", (req, res) -> {
            res.redirect("index.html");
            return null;
        });

        Spark.post("/api/message", (req, res) -> {
            return "Hi, Kirk, this API call worked";
        });

        Spark.post("/number/employees", (req, res) -> {
            // Retrieve the value of 'n' from the request
            int n = Integer.parseInt(req.queryParams("n"));

            // Use 'n' as needed in your HalfHourIntervals or other logic
            
            return schedule.createSchedule(n);
            // return "Alli, Station Manager, 6-9.";
        });
    }
}
